config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root to: 'lists#index'

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  # # The comment of a bookmark cannot be shorter than 6 characters.
  validates :comment, length: { minimum: 6 }, presence: true

  # # A bookmark must be linked to a movie and a list, and the [movie, list] pairings should be unique.
  # validates :movie, :list, presence: true || NOT IN NOEMI'S CODE
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  # FYI THE ORDER MATTERS HERE. IF YOU FLIP THE TWO BELOW, YOU GET AN ERROR.
  has_many :bookmarks, dependent: :destroy
  # has_many :movies, through: :bookmarks
  has_one_attached :photo
  # A list must have a unique name.
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks # BUT WHY
  has_many :lists, through: :bookmarks

  # A movie must have a unique title and an overview.
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list) # BUT WHY!!!
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container my-5">
  <div class="px-5 py-3 my-3">
    <h1 class="text-center semibold"><%= "🎬 Select the movie to add to #{@list.name}" %></h1>

    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.association :movie, collection: Movie.all, include_blank: false %>
      <%= f.input :comment %>
      <%= f.submit("🩷 Add this movie to your #{@list.name}", class: 'btn btn-success') %>
    <% end %>

    <div class="mt-3">
      <p><%= link_to "👈 Back to #{@list.name}", list_path(@list), class: 'btn btn-secondary' %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<%= stylesheet_link_tag "application", "data-turbo-track": Rails.env.production? ? "reload" : "" %>
  <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container my-5">
  <h1>Welcome to your movies list!</h1>

  <p><%= link_to "➕ Create a new movie list here!", new_list_path, class: "text-decoration-none" %></p>

  <% @lists.each do |list| %>
    <ul>
      <li><%= link_to "#{list.name}", list_path(list), class: "text-decoration-none" %></li>
    </ul>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="container my-5">
  <div class="px-5 py-3 my-3">
    <h1 class="text-center semibold">✍️ Create your new list!</h1>
    <%= simple_form_for @list do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file, input_html: { multiple: true } %>
      <%= f.submit("🩷 Add your new list", class: 'btn btn-success') %>
    <% end %>

    <div class="mt-3">
      <p><%= link_to '👈 Back to all lists', lists_path, class: 'btn btn-secondary' %></p>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container my-5">
  <h1>📋 <%= @list.name %></h1>
    <div>
      <% @list.bookmarks.each do |bookmark| %>
        <div>
          <% if @list.photo.attached? %>
            <%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
          <% else %>
            <img src="https://plus.unsplash.com/premium_photo-1762518577411-27d3695b994b?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
          <% end %>
          <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Delete #{bookmark.movie.title}? 🤔" } do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
          <p class="fw-light"><%= bookmark.movie.rating %></p>
          <h3 class="fw-semibold"><%= bookmark.movie.title %></h3>
          <p class="fw-light"><%= bookmark.movie.overview %></p>
        </div>
      <% end %>
    </div>

  <div class="mt-3">
    <p><%= link_to '👉 Bookmark movies to this list', new_list_bookmark_path(@list), class: 'btn btn-success' %></p>
    <p><%= link_to '👈 Back to all lists', lists_path, class: 'btn btn-secondary' %></p>
  </div>
</div>